### PR TITLE
VP-945 Fix loadGoals test occasionally failing

### PR DESCRIPTION
**Pull request by guttmann**
## I do solemnly swear that I have:

- [x] Run `npm test` and all the tests pass.
- [x] Run `npm run lint` and there are no warnings.
- [x] Not decreased the overall test coverage?
- [x] Included the Jira ID and description in the PR title

## Proposed Changes? 🤔

1. The loadGoals test isn't `await`ing the promise returned by the `loadGoals` function so sometimes the test will fail because not all goal records are loading in time.

### CODE REVIEW

**Comment by bernesemountaindog** [comment]
This lint package can be quite useful: https://www.npmjs.com/package/eslint-plugin-promise
It'll highlight promises which are left dangling

**Comment by avowkind** [comment]
> This lint package can be quite useful: https://www.npmjs.com/package/eslint-plugin-promise
> It'll highlight promises which are left dangling

It would be nice to have - but will it work alongside jsstandard?  we don't want two competing lints.

**Comment by guttmann** [comment]
> > This lint package can be quite useful: https://www.npmjs.com/package/eslint-plugin-promise
> > It'll highlight promises which are left dangling
> 
> It would be nice to have - but will it work alongside jsstandard? we don't want two competing lints.

I've had a quick look - it doesn't look like we can do it while using `standard` itself (i.e. running the `standard` command for linting). However, there are a couple of ways we could achieve it without maintaining two competing linting tools.

1. Switch over to using `standardx` (https://github.com/standard/standardx) which allows customisation of eslint plugins and rules
2. Switch to `eslint` using the standard config (https://www.npmjs.com/package/eslint-config-standard) which would then also allow us to customise plugins and add additional rules

It looks like the move to `standardx` would be simpler (and there is a migration tool available too: https://github.com/josephfrazier/standard-eject).

It's really up to you though @avowkind if you think the benefits of being able to add additional rules (like the promise checks) is worth the effort of switching over.

**Comment by avowkind** [comment]
Its a possibility - but maybe for another time.

**Pull request merged**
