### PR TITLE
Issue/vp 374/op card status tag

### PR DESCRIPTION
**Pull request by AidanTheDeveloper**
Made progress towards VP-374

A users interest status is now displayed in "strong" tags on opCards.

In this pull request I did the following:
Modified landing page to pass "me" prop to OpListSection
Modified OpListSection to pass interests to OpList
Modified OpList to pass interest status to OpCard
Modified OpCard to take an interestStatus parameter and display it in strong tags

Also added tests for all the changes I have made to ensure that behaviour is not modified

Although I have not implemented the Antd badges, the components have been wired up so that when this change is done it should be visible in the landing page.

## Screenshots 📷
 
image

### CODE REVIEW

**Comment by AidanTheDeveloper** [comment]
Modified styles to make it look what I think is a little nicer, still no antd badges though
image

**Comment by avowkind** [comment]
I propose closing this PR and that we start again with just the style changes on the home page.

**Comment by AidanTheDeveloper** [comment]
Yeah that sounds pretty fair at this point, I think I went a little too far down the wrong rabbit hole 😅

**Comment by avowkind** [comment]
That happens to us all and is not a problem.  I suggest (if you have the time) starting a new branch and just copying over the style changes to the OpList in Home based on the persons interests having being added to each op.We don’t need to show this in search results and landing page. (At this time).Regards Andrew On 1/10/2019, at 17:18, Aidan Harris <notifications@github.com> wrote:Yeah that sounds pretty fair at this point, I think I went a little too far down the wrong rabbit hole 😅—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by avowkind** [comment]
I'm going to close this PR.  Please open a new one as we discussed above.

**Pull request closed without merging**
