### PR TITLE
Vp 350 display order of events on landing page

### PR DESCRIPTION
**Pull request by n8-dev**
# Pull Request Template (VP-123)

## Proposed Changes? 🤔
1.  Update the DB factory to have some variety for more _"real"_ data
2. Update landing page to use logic from search page for date range of this morning to arbritary date. 
3. 

## Additional Info.🧐
* Arbritary date is some months in future and easily changed in a variable.
* there is an issue with the range filter. Please see VP-575 https://voluntarily.atlassian.net/browse/VP-575%7Chttps://voluntarily.atlassian.net/browse/VP-575%7Csmart-link

### CODE REVIEW

**Comment by n8-dev** [comment]
My bad, currently at kawaiicon in Wellington and submitted the PR on my phone.
Will run them next time

**Comment by n8-dev** [comment]
Been swamped with some work, will try and get to this soon.

**Comment by avowkind** [comment]
No worries, although the longer you wait the further behind master you’ll fall ;)
Andrew

**Comment by avowkind** [comment]
Closing this PR it is now too far behind master.
Suggest starting a new branch and copying changes over as there's not too many.

**Pull request closed without merging**
