### PR TITLE
VP-1379 create generic closing state

### PR DESCRIPTION
**Pull request by waltzaround**
## I do solemnly swear that I have:
- [x] Run `npm test` and all the tests pass.
- [x] Run `npm run lint` and there are no warnings.
- [] Not decreased the overall test coverage?
- [x] Included the Jira ID and description in the PR title

## Proposed Changes? 🤔
1. created dumb activity creation close component
2. created dumb org school creation close component 

## Screenshots 📷
 
image
image

### CODE REVIEW

**Comment by avowkind** [comment]
Walt these are basically the same options as the goal cards.  Do you think that the panels can be generated as a different view component on the goal cards?  These are not the sort of thing we want hard coded?

**Comment by waltzaround** [comment]
@avowkind Agree but how do we want to store the markup?

**Comment by avowkind** [comment]
The card is in the database we can store html there, we can add more fields if we want a long or short form of the card. 

I’m concerned that clicking these mini-cards bypasses the features of the goal cards - the in progress, the instructions, the completion tests etc. 

Have you considered reworking the personal goals section of the home page to look like this?

**Comment by waltzaround** [comment]
I dont think these need to be as complex as goalcards imho - not to mention most of the actions on the minicards are very small (ie: share the event) and do not need to be tracked

**Pull request closed without merging**
