### PR TITLE
VP-882/refactor_footer: changed divs and a tags to ul li

### PR DESCRIPTION
**Pull request by careykwan**
## I do solemnly swear that I have:
- [x] Run `npm test` and all the tests pass.
- [x] Run `npm run lint` and there are no warnings.
- [x] Not decreased the overall test coverage?
- [x] Included the Jira ID and description in the PR title

## Proposed Changes? 🤔
1. changed footer links to a ul
2. 
3. 

## Additional Info.🧐

Any additional info goes here

### CODE REVIEW

**Comment by bernesemountaindog** [comment]
This has caused a regression in the footer. Items are no longer `a` links.

**Comment by bernesemountaindog** [comment]
We'll need to raise a new card to change all the `<a href="..."></a>` tags to instead use `<Link />` component.

See: https://nextjs.org/learn/basics/navigate-between-pages

There are a few examples of this around the website, which is why you sometimes see the app reloading completely instead of acting like a single page app.

**Comment by bernesemountaindog** [comment]
I think we should remove the margin/padding the new `ul` has introduced. As the 'columns' are now indented - not so much an issue in desktop, but in mobile with the limited space it becomes noticeable.

**Comment by careykwan** [comment]
> I think we should remove the margin/padding the new `ul` has introduced. As the 'columns' are now indented - not so much an issue in desktop, but in mobile with the limited space it becomes noticeable.

No worries I will do this now, however im not sure what is cause the test to fail?

**Pull request merged**
